import {SourceText} from './SourceText';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,CheckCircle2,ChevronDown,FileArchive,Folder,Link,LockKeyhole,Package,Route,ShieldCheck,WandSparkles} from 'lucide-react';
import {Tabs} from 'radix-ui';
import {type Ask,AssistantNotice,Heading,Help,More,Page,Primary,Reveal,SectionTabs} from './shared';
import {useClient} from './client-state';
import {buildSkillExportAction} from '../lib/data';
import {recommendForSkillWorkshop} from '../lib/skill-workshop';
import {workshopRequest,workshopAction} from './workshop-request.mjs';

const formats=[{id:'zip',label:'ZIP 压缩包',note:'方便发给别人',Icon:FileArchive},{id:'folder',label:'独立文件夹',note:'方便查看和修改',Icon:Folder},{id:'link',label:'分享链接',note:'生成前确认发布位置',Icon:Link},{id:'local',label:'先留在本机',note:'暂时不分享',Icon:LockKeyhole}];
export default function Workshop({ask}:{ask:Ask}){
  const {assistant,act}=useClient();
  const snapshot=assistant?.snapshot;
  const methods=[...(snapshot?.sops||[]).map(item=>({...item,sourceKind:'sop' as const})),...(snapshot?.capabilities||[]).map(item=>({...item,sourceKind:'capability' as const}))].map(item=>({...item,name:item.title,type:item.sourceKind==='sop'?'固定流程 · SOP':'能力',when:(item.triggers||[]).join('、'),recommendation:recommendForSkillWorkshop(item.sourceKind,{...item,reliability:item.maturity||item.reliability,approvalState:item.approval_state,approvedByUser:item.approved_by_user,activationBasis:item.activation_basis} as any)}));
  const ownSkills=(snapshot?.skills.exports||[]).map(item=>({...item,name:item.title,status:item.state==='review'?'需要复核':item.state==='draft'?'待完成':'内容已检查',tone:item.state==='ready'?'green':'amber',help:item.state==='ready'?'内容已通过检查。可以请 Agent 确认文件位置，再准备压缩包、文件夹或分享链接。':item.state==='review'?'这份 Skill 还有需要确认的地方。请 Agent 说明问题，再继续完善。':'内容还没整理完。可以请 Agent 接着做，不用重新生成。',action:buildSkillExportAction({id:item.id,state:item.state as any,deliveryMethod:item.delivery_method||'',deliveryState:item.delivery_state||'unselected'}).buttonLabel,body:buildSkillExportAction({id:item.id,state:item.state as any,deliveryMethod:item.delivery_method||'',deliveryState:item.delivery_state||'unselected'}).text,delivery:item.delivery_state==='artifact-ready'?'分享文件已准备':item.delivery_state==='link-ready'?'分享链接已准备':item.delivery_state==='stale'?'分享文件需要更新':item.delivery_state==='unselected'?'分享方式待选择':''}));
  const installedSkills=(snapshot?.skills.items||[]).map(item=>({...item,name:item.title,status:item.state==='available'?'可以使用':item.state==='review'?'需要复核':'暂时不可用',tone:item.state==='available'?'green':'amber',help:item.state==='available'?'已接入这份助手。把要做的任务告诉 Agent，它会判断这份 Skill 是否适用。':'请 Agent 查清这份 Skill 为什么暂时不能用，再帮你处理。其他 Skill 可以继续使用。',action:item.state==='available'?'让 Agent 使用这份 Skill':'让 Agent 检查并处理',body:`请读取本助手已接入的 Skill「${item.title}」（ID：${item.id}），核对用途、实际入口和当前状态。${item.state==='available'?'结合我当前的任务使用；不明确时先询问。':'解释问题并在现有授权内修复；不删除原内容，不停用无关能力。'}`}));
  const [tab,setTab]=useState('share'),[selected,setSelected]=useState(''),[format,setFormat]=useState('zip');
  const [sourceType,setSourceType]=useState('folder'),[locations,setLocations]=useState<Record<string,string>>({folder:'',zip:'',link:''}),[error,setError]=useState(''),[picking,setPicking]=useState(false);
  const picker=useRef({busy:false,revision:0});
  const location=locations[sourceType]||'';
  useEffect(()=>()=>{picker.current.revision++;},[]);
  const editLocation=(value:string)=>{picker.current.revision++;setLocations(values=>({...values,[sourceType]:value}));setError('');};
  const changeSource=(kind:string)=>{picker.current.revision++;setSourceType(kind);setError('');};
  const chooseSource=async()=>{
    if(picker.current.busy||sourceType==='link')return;
    picker.current.busy=true;const revision=++picker.current.revision,kind=sourceType;setPicking(true);setError('');
    try{
      const selected=await act('choose-skill-source',{sourceType:kind});
      if(revision===picker.current.revision&&selected)setLocations(values=>({...values,[kind]:selected}));
    }catch(e){if(revision===picker.current.revision)setError(`没能打开选择窗口。可以重试，或直接粘贴完整路径。${(e as Error).message||''}`);}
    finally{picker.current.busy=false;setPicking(false);}
  };
  const [mineTab,setMineTab]=useState('own'),[open,setOpen]=useState<string|null>(null);
  const method=methods.find(m=>m.id===selected)||methods[0];
  const askImport=()=>{if(!location.trim()){setError(sourceType==='link'?'请粘贴 Skill 的网页链接。':`请先选择${sourceType==='zip'?' ZIP 文件':' Skill 文件夹'}，也可以粘贴完整路径。`);return;}setError('');ask({title:'检查这份 Skill',preferredDestination:'new',...workshopAction('skill.install-shared',{source_location:location.trim(),source_type:sourceType})});};
  return <Page><Heading title="Skill " accent="工坊">把常用方法做成 Skill，也能导入别人分享的 Skill。<Help label="Skill 是什么？">Skill 是一份给 Agent 使用的方法包，里面说明适合做什么、具体怎么做。你可以分享自己的，也可以安装别人分享的。</Help></Heading>
    <AssistantNotice/>
    <SectionTabs value={tab} onChange={setTab} label="Skill 工坊分区" items={[{id:'share',label:'整理并分享'},{id:'import',label:'接入别人的 Skill'},{id:'mine',label:'我的 Skill'}]}/>
    {tab==='share'&&!method&&<div className="empty-state"><p>{assistant?'还没有可以整理的方法。保存为 SOP 或能力后，就能在这里选择并做成 Skill。':'先在上方选择助手文件夹，查看可以整理的方法。'}</p></div>}
    {tab==='share'&&method&&<div className="workshop-layout"><section className="method-list"><div className="section-label"><h2>Agent 推荐整理的 Skill</h2><Help label="为什么推荐这些？">这里列出已保存的方法供你选择。Agent 会读取正文，判断哪些步骤适合整理给别人用；不做成 Skill，也不影响原来的方法。</Help></div><p className="muted">先选一个你想分享的方法。</p><div className="method-options">{methods.map(m=><button key={m.id} className={`method-option ${method?.id===m.id?'selected':''}`} onClick={()=>setSelected(m.id)} aria-pressed={method?.id===m.id}><span className="method-symbol"><Route size={22}/></span><span><small>{m.type}</small><strong><SourceText>{m.name}</SourceText></strong><span><SourceText>{m.summary}</SourceText></span></span><ArrowUpRight size={18}/></button>)}</div><p className="quiet-caption">原方法会保留，私人信息由 Agent 在副本中处理。</p></section>
    <section className="prepare-sheet"><Reveal kind="selection" key={method.id}><div className="sheet-caption"><WandSparkles size={20}/><span>把这个方法整理为 Skill</span></div><h2><SourceText>{method.name}</SourceText></h2><p className="muted">{method.recommendation.label}<Help label="当前建议的依据">{method.recommendation.help}</Help></p><More title="看看会整理哪些内容"><p><SourceText>{method.when}</SourceText></p><p><SourceText>{method.summary}</SourceText></p><p>{method.recommendation.reason}</p><p>记录编号：{method.id}。Agent 会读取原方法，保留有用的步骤，再整理成适合分享的版本。</p></More></Reveal>
      <div className="format-heading"><h3>你想怎样分享？</h3><Help label="选链接会直接发布吗？">不会。Agent 会先问你想发布到哪里、哪些内容可以公开，再准备 Skill；发布前还会与你确认。也可以先留在本机。</Help></div>
      <Tabs.Root value={format} onValueChange={setFormat}><Tabs.List className="format-options" aria-label="分享方式">{formats.map(f=><Tabs.Trigger key={f.id} value={f.id}><f.Icon size={23}/><span><strong>{f.label}</strong><small>{f.note}</small></span>{format===f.id?<CheckCircle2 size={19}/>:<span className="radio-dot"/>}</Tabs.Trigger>)}</Tabs.List></Tabs.Root>
      <div className="privacy-line"><ShieldCheck size={19}/><p>Agent 会先复制原方法，自动去除私人信息，再整理并检查 Skill。<strong>原方法保留，不会自动上传或发送。</strong></p></div>
      <Primary onClick={()=>ask({title:'整理为可分享的 Skill',itemId:method.id,preferredDestination:'new',...workshopAction('skill.create-from-asset',{asset_id:method.id,delivery_format:format})})}>让 Agent 整理为 Skill</Primary>
    </section></div>}
    {tab==='import'&&<div className="import-layout"><div className="import-intro"><span className="large-symbol"><Package size={42} strokeWidth={1.3}/></span><h2>把别人的 Skill，<br/>用到你的助手里。</h2><p>选一个文件夹、压缩包，或粘贴链接。<br/>Agent 会先检查，再引导你安装。</p><More title="已经有旧版怎么办？"><p>Agent 会先判断是不是同一个 Skill 的新版，说明变化并保留你的设置和资料。来源不清楚时会先问你，不会直接覆盖旧版。</p></More></div><section className="import-form"><h2>Skill 放在哪里？</h2><SectionTabs value={sourceType} onChange={changeSource} label="Skill 来源类型" items={[{id:'folder',label:'文件夹'},{id:'zip',label:'ZIP 文件'},{id:'link',label:'网页链接'}]}/>
      <label htmlFor="skill-location">{sourceType==='link'?'Skill 的网页链接':sourceType==='zip'?'ZIP 文件位置':'Skill 文件夹位置'}</label>
      <div className="skill-location-field"><input id="skill-location" value={location} title={location||undefined} onChange={e=>editLocation(e.target.value)} placeholder={sourceType==='link'?'例如：Skill 所在的 GitHub 页面':(window.carryClient?'点击右侧图标选择，或粘贴路径':'粘贴完整路径，或点下方“帮我找到 Skill”')} aria-invalid={!!error} aria-describedby={error?'import-error':'skill-location-note'}/>{sourceType!=='link'&&window.carryClient&&<button className="source-picker" onClick={()=>void chooseSource()} disabled={picking} aria-label={picking?'正在选择…':sourceType==='zip'?'选择 ZIP 文件':'选择文件夹'} title={picking?'正在选择…':sourceType==='zip'?'选择 ZIP 文件':'选择文件夹'}><Folder size={20}/></button>}</div>
      {error&&<p id="import-error" className="input-error" role="alert">{error}</p>}<p id="skill-location-note" className="field-note">选好后复制请求，发给 Agent 检查。不会自动上传或安装。</p><Primary onClick={askImport} disabled={picking}>让 Agent 检查这份 Skill</Primary><button className="text-button" onClick={()=>ask({title:'先找到 Skill 的位置',preferredDestination:'new',body:workshopRequest('skill.install-shared',{source_location:'',need_help:'请先引导我找到 Skill 的位置，一次只问一个问题。'})})}>帮我找到 Skill<ArrowUpRight size={17}/></button><div className="privacy-line"><ShieldCheck size={19}/><p>Agent 会检查用途、脚本和所需权限。<strong>发现问题只处理这份 Skill，其他能力照常使用。</strong></p></div></section></div>}
    {tab==='mine'&&<section className="skills-shelf"><div className="shelf-head"><SectionTabs value={mineTab} onChange={v=>{setMineTab(v);setOpen(null);}} label="我的 Skill 类型" items={[{id:'own',label:'我整理的'},{id:'installed',label:'已接入的'}]}/><span className="muted">点开查看用途、状态和可做的操作。</span></div>{!(mineTab==='own'?ownSkills:installedSkills).length&&<div className="empty-state"><p>{!assistant?'先选择助手文件夹，查看已有的 Skill。':mineTab==='own'?'还没有整理过 Skill。可以在“整理并分享”中选择一个方法。':'还没有接入 Skill。可以从“接入别人的 Skill”开始。'}</p></div>}{(mineTab==='own'?ownSkills:installedSkills).map(s=><article className="skill-row" key={s.id}><button className="skill-overview" onClick={()=>setOpen(open===s.id?null:s.id)} aria-expanded={open===s.id}><span className="skill-book"><Package size={25}/></span><span className="skill-name"><strong><SourceText>{s.name}</SourceText></strong><span><SourceText>{s.summary}</SourceText></span></span><span className={`status-pill ${s.tone}`}>{s.status}</span><ChevronDown className={open===s.id?'rotated':''} size={20}/></button>{open===s.id&&<Reveal><div className="skill-details"><div className="reveal-item"><h3>当前状态<Help label={s.status}>{s.help}</Help></h3><p>{s.help.replace('示例：','')}</p>{'delivery' in s&&typeof s.delivery==='string'&&<p>{s.delivery}</p>}</div><div className="reveal-item"><Primary onClick={()=>ask({title:s.action,itemId:s.id,body:s.body,})}>{s.action}</Primary><small>复制请求，再发给你想用的 Agent。</small></div></div></Reveal>}</article>)}</section>}
  </Page>;
}
