// Interface copy only. Never translates saved user content or creates a second protocol.
export const APP_ENGLISH:Record<string,string>={
  "让你的积累": "Keep what you learn",
  "一直待在你身边。": "Always by your side.",
  "我的积累": "My collection",
  "AI Carry · 随身助手": "AI Carry · Your portable assistant",
  "AI Carry 保存你的习惯、记忆和常用方法。": "AI Carry keeps your habits, memories and trusted methods.",
  "换用其他 Agent，这些积累也能带过去。": "Take them with you when you switch Agents.",
  "查看我的积累": "View my collection",
  "先选使用经验，再选助手方向。": "Choose your experience level, then an assistant direction.",
  "从总览进入功能": "Explore AI Carry",
  "换一个 Agent": "Switch Agent",
  "属于你的方法，跟着你走。": "Your methods. Wherever you go.",
  "字体：MiSans · Xiaomi": "Type: MiSans · Xiaomi",
  "这一页没能打开": "This page could not open",
  "助手资料还在。可以先用其他页面，再回来重试。": "Your files are safe. Use another page and retry this one later.",
  "返回总览": "Back to overview",
  "AI Carry 总览": "AI Carry overview",
  "主要页面": "Main pages",
  "中文 / English": "中文 / English",
  "中": "中",
  "当前窗口展示虚构示例，不会修改你的助手": "Fictional examples; your assistant is not changed",
  "演示数据": "Demo",
  "正在读取资料": "Reading files",
  "本地资料 · 只读查看": "Local files · Read-only",
  "本地客户端": "Desktop app",
  "本地网页版": "Local web view",
  "系统已减少动态": "Reduced motion is on",
  "播放首屏动效": "Play home animation",
  "暂停首屏动效": "Pause home animation",
  "助手设置": "Assistant settings",
  "查看如何使用客户端": "How to use AI Carry",
  "使用说明": "How it works",
  "点击卡片，查看对应的积累": "Click a card to open that collection",
  "点卡片，看积累": "Pick a card. Explore your collection.",
  "查看": "View",
  "全部": "All",
  "待办与": "Tasks & ",
  "继续还没完成的任务。": "Pick up unfinished work.",
  "看看哪些新发现值得记住，或整理成常用方法。": "Choose discoveries worth keeping or turning into methods.",
  "请 Agent 整理这条建议": "Ask Agent to review this idea",
  "定期检查助手的记忆、方法和工作方式。": "Review your assistant's memories, methods and ways of working.",
  "请 Agent 开始这项改进": "Ask Agent to start this improvement",
  "查看未完成的任务、待整理的新发现，以及助手的改进计划。": "Unfinished tasks, new discoveries and plans to improve your assistant.",
  "保存前先询问": "Ask before saving",
  "低风险内容可自动保存": "Low-risk learning can be saved automatically",
  "尚未设置": "Not set yet",
  "先选择助手文件夹": "Choose an assistant folder first",
  "学习方式决定 Agent 保存新发现前，是否需要先问你。": "The learning policy determines when the Agent asks before saving a discovery.",
  "这个学习方式是什么意思？": "What does this learning policy mean?",
  "选择“保存前先询问”，Agent 会先征求你的意见；按风险处理时，已授权的低风险内容可以自动保存。两种方式都会说明记住了什么，已有积累不会被清空。": "With “Ask before saving”, the Agent checks with you first. Risk-based learning can save already-authorized, low-risk discoveries automatically. Both report what was saved and keep your existing collection.",
  "了解并调整学习方式": "Review the learning policy",
  "请 Agent 帮我调整": "Ask Agent to adjust it",
  "待办与成长分区": "Tasks and growth sections",
  "已保存的计划": "Saved plan",
  "待整理": "To review",
  "已保存的待办": "Saved task",
  "收起": "Collapse",
  "从这里继续": "Continue from here",
  "具体做什么": "What this involves",
  "查看依据与范围": "See context and scope",
  "记录编号：": "Record ID: ",
  "。Agent 会读取这项记录的最新进度，避免从头重做。": ". The Agent reads the latest progress so you do not start over.",
  "复制请求，再到 Agent 中发送。": "Copy the request, then send it in your Agent.",
  "还没有待办。可以让 Agent 记下以后要继续的事。": "No saved tasks yet. Ask your Agent to keep work you want to continue later.",
  "还没有学习建议。工作中发现值得积累的内容时，Agent 会告诉你。": "No learning ideas yet. The Agent will tell you when it finds something worth keeping.",
  "还没有长期改进计划。可以和 Agent 商量哪些方面需要定期检查。": "No improvement plans yet. Discuss with your Agent what is worth reviewing regularly.",
  "先在上方选择助手文件夹，查看已保存的任务和计划。": "Choose your assistant folder above to see saved tasks and plans.",
  "Agent 会简短汇报：这次用上了什么，又记住了什么。": "Your Agent briefly reports what it used and what it learned.",
  "学习和使用会怎样告诉我？": "How are learning and use reported?",
  "用过的内容会说明这次帮了什么忙；新学到的内容会说明是否已保存、以后什么时候用。只是读到一条记录，不会算作已经用上。": "Used knowledge is linked to what it helped with. New learning states whether it was saved and when to use it. Reading a record alone is not the same as using it.",
  "这套流程怎么做": "How this workflow works",
  "这项能力怎么用": "How to use this capability",
  "记录了什么经验": "What this experience records",
  "正在读取这一条的正文…": "Reading this record…",
  "什么时候用": "When to use it",
  "一定要说这句话吗？": "Do I need to say those exact words?",
  "不用。Agent 会根据你正在做的事，查找相关记忆和方法。你也可以点“让 Agent 用这条”，明确告诉它参考哪一条。": "No. The Agent looks for relevant memories and methods based on your task. You can also choose “Ask Agent to use this” to select a particular record.",
  "这条记录还没写明使用场景，可以让 Agent 结合当前任务判断。": "No usage context is recorded yet. Ask the Agent to assess it for your current task.",
  "还没有实际使用记录": "No real use recorded yet",
  "已在实际任务中使用": "Used in a real task",
  "已通过多次任务验证": "Validated across several tasks",
  "已在不同 Agent 或环境中验证": "Validated across Agents or environments",
  "实践情况待确认": "Usage evidence needs review",
  "查看来源与补充": "Source and more",
  "来自你选择的助手文件夹。": "From your selected assistant folder.",
  "条目：": "Record: ",
  "这里是演示正文，不是你的真实记录。": "This is example content, not your records.",
  "这里显示已保存的原始内容。": "Saved source content is shown here.",
  "让 Agent 用这条": "Ask Agent to use this",
  "我的": "My ",
  "积累": "collection",
  "记住的习惯、做熟的方法，都在这里。": "The habits and methods you have built up, together in one place.",
  "做相关任务时，Agent 会主动参考。": "Your Agent draws on these when the task is relevant.",
  "也可以选一条，让 Agent 参考它。": "Or choose a record for the Agent to use.",
  "Agent 会怎样用上？": "How does the Agent use this?",
  "Agent 会按当前任务查找相关记忆与方法。真正用到时，会简短告诉你；不合适的内容不会照搬。你也可以在这里指定某一条。": "The Agent looks up memories and methods for the current task, reports what it actually uses, and does not copy unsuitable advice. You can also select a record here.",
  "助手积累列表": "Assistant collection",
  "按类型查看积累": "Filter collection by type",
  "搜索积累": "Search collection",
  "搜索名称或内容": "Search names or content",
  "清空搜索": "Clear search",
  "没有找到匹配的内容": "No matching records",
  "这里还没有积累": "Nothing saved here yet",
  "点上方“选择助手文件夹”，查看已有的记忆和方法。": "Choose an assistant folder above to see saved memories and methods.",
  "换个词试试，或清空筛选再找。": "Try another word or clear the filters.",
  "以后保存的记忆、方法和经验，会显示在这里。": "Memories, methods and experiences saved later will appear here.",
  "清空筛选": "Clear filters",
  "执行任务：复制请求，发给 Agent": "To act: copy the request and send it to your Agent",
  "关闭请求预览": "Close request preview",
  "让 Agent 参考这一条": "Ask Agent to refer to this",
  "这里先预览请求内容，没有发送给 Agent。": "Preview only. Nothing has been sent to an Agent.",
  "返回查看": "Back to the record",
  "请一步步讲解，尽量不用术语。": "Guide me step by step, with as little jargon as possible.",
  "把关键步骤讲清楚，必要时再解释。": "Explain key steps and add details when needed.",
  "基础操作不用细讲，直接讨论怎么做。": "Skip the basics and get into the work.",
  "处理不同事情，记住你的习惯和常用方法。": "Handle different tasks while keeping your habits and methods.",
  "围绕你的职业或领域，积累更专门的方法。": "Build specialized methods for your profession or field.",
  "让 Agent 了解你的需要，再一起选方向。": "Let the Agent understand your needs, then choose together.",
  "创建你的": "Create your",
  "AI 助手。": "AI assistant.",
  "先选使用经验和大致用途，": "Choose your experience and intended use.",
  "再让 Agent 帮你完善创建方案。": "Your Agent will help shape the setup.",
  "使用经验": "Experience",
  "核对选择": "Review choices",
  "你对 Agent 熟悉吗？": "How familiar are you with Agents?",
  "你希望助手主要帮什么忙？": "What would you like help with?",
  "这会影响什么？": "What does this change?",
  "还没想好可以选什么？": "What if I am not sure yet?",
  "Agent 会据此调整讲解的详细程度。不会限制功能，创建后也能改。": "This adjusts how much explanation the Agent gives, not which features you can use. You can change it later.",
  "选“先帮我判断”，让 Agent 先了解你的工作和需要，再帮你比较通用助手与专业助手。方向由你决定。": "Choose “Help me decide” to discuss your work and needs, then compare general and specialized assistants. You make the choice.",
  "选最接近你现在情况的一项。": "Choose what fits you best right now.",
  "选一个大致方向就好，还没想清楚也没关系。": "A broad direction is enough. It is fine to be unsure.",
  "先不创建": "Not now",
  "下一步": "Next",
  "修改": "Change",
  "把这些选择发给 Agent": "Send these choices to your Agent",
  "Agent 会继续了解你的需要，": "The Agent will ask about your needs,",
  "给出创建方案，确认后再创建。": "propose a setup and create it after you confirm.",
  "请 Agent 引导创建助手": "Ask Agent to guide setup",
  "查看并复制创建请求": "Preview and copy setup request",
  "点击后可预览请求，再复制到 Agent 对话中发送。": "Preview the request, then copy it into your Agent conversation and send.",
  "正在读取助手资料…": "Reading assistant files…",
  "还没有选择助手资料": "No assistant folder selected",
  "这些是虚构示例，可以点开体验，不会修改你的助手。": "Explore these fictional examples. Your assistant is not changed.",
  "显示的是这份助手保存在本机的资料。": "These are the files saved locally for this assistant.",
  "先选择 AI Carry 助手文件夹，这里会显示已有资料，不会修改原文件。": "Choose an AI Carry folder to view saved content. The original files are not changed.",
  "查看资料提示": "See data notice",
  "资料存放位置": "File location",
  "重新读取": "Reload files",
  "更换文件夹": "Change folder",
  "选择助手文件夹": "Choose assistant folder",
  "查看补充说明": "More information",
  "没能自动复制。请点“选中全文”，手动复制后发给 Agent。": "Automatic copying failed. Choose “Select all”, copy manually and send to your Agent.",
  "这里预览的是演示请求，示例条目不对应真实文件。": "This is a demo request. The example records do not refer to real files.",
  "点击“复制请求”，粘贴到你想用的 Agent 对话中，再发送。": "Click “Copy request”, paste it into the Agent conversation you want, then send.",
  "这件事可以在 Agent 中另开对话处理，不必打断手头的任务。": "You can handle this in a new Agent conversation without interrupting your current task.",
  "补充要求（可选）": "Extra details (optional)",
  "还有什么要求？比如内容主题、输出格式或保存位置。": "Add a topic, output format, save location or other details.",
  "完整请求": "Full request",
  "收起全文": "Show less",
  "展开完整请求": "Show full request",
  "选中全文": "Select all",
  "再次复制": "Copy again",
  "正在复制…": "Copying…",
  "复制演示请求": "Copy demo request",
  "复制请求": "Copy request",
  "原请求已保留，可以选中全文手动复制。": "The request is still here. Select all to copy it manually.",
  "演示请求已复制，没有执行任何任务。": "Demo request copied. No task was executed.",
  "可查看完整流程；此窗口不会调用 Agent 或修改助手资料。": "Explore the workflow. This window does not call an Agent or change assistant files.",
  "已复制。粘贴到你想用的 Agent 对话中，再发送。": "Copied. Paste into your chosen Agent conversation, then send.",
  "复制的是完整请求，折叠的内容也会带上。": "The entire request is copied, including the collapsed text.",
  "复用已有偏好": "Reuse existing preferences",
  "重新生成看板": "Rebuild dashboard",
  "我的助手，": "My assistant, ",
  "当前状态。": "right now.",
  "查看这份助手的设置，也可以让 Agent 帮你调整。": "Review this assistant's settings or ask the Agent to adjust them.",
  "助手": "Assistant",
  "尚未读取": "Not loaded",
  "版本": "Version",
  "尚未创建": "Not created yet",
  "让 Agent": "Ask Agent to ",
  "核对当前模型": "check the current model",
  "帮我复用偏好": "help reuse preferences",
  "这会直接修改助手吗？": "Does this change the assistant directly?",
  "不会。你先预览请求，再复制到想用的 Agent 中发送。Agent 会按实际资料和本次授权处理；不需要重新创建助手。": "No. Preview and copy a request, then send it to your Agent. The Agent works with the actual files and your authorization; it does not recreate the assistant.",
  "单独导出私人资料，方便在另一份助手中恢复。": "Export private files separately for restoring in another assistant.",
  "把之前导出的私人资料恢复到这台电脑。": "Restore previously exported private files on this computer.",
  "让 Agent 核对备份内容，排除隐私后再决定是否上传。": "Ask the Agent to review the backup and exclusions before you decide whether to upload.",
  "迁移与": "Move & ",
  "安全": "safety",
  "换 Agent、换电脑、备份资料或检查更新，都从这里开始。": "Switch Agents or computers, back up files, or check for updates.",
  "选择迁移方式": "Choose a move",
  "同一台电脑，接着用这份 AI Carry。": "Keep using this AI Carry on the same computer.",
  "换一台电脑": "Move to a new computer",
  "把助手与本地资料一起带走。": "Take your assistant and local files with you.",
  "不用重新创建助手": "No need to create another assistant",
  "确认要带走的资料": "Choose what to take",
  "把接手请求发给新 Agent，让它读取现有助手的习惯、方法和进度，再继续工作。": "Send the handoff request to your new Agent. It reads the assistant's habits, methods and progress before continuing.",
  "Agent 会先列出已知资料，你只需核对并补充遗漏，再由它准备迁移包。": "The Agent lists known files first. Review them and add anything missing, then it prepares the migration package.",
  "怎样交给新 Agent？": "How do I hand this to a new Agent?",
  "迁移包里有什么？": "What is in the migration package?",
  "在新 Agent 中打开这份助手文件夹，再粘贴接手请求。它需要能读取本地文件；找不到文件夹时，请把位置告诉它。": "Open this assistant folder in the new Agent and paste the handoff request. The Agent needs local file access; give it the folder location if necessary.",
  "包含助手、你确认携带的本地资料和恢复说明。新电脑上需要重新安装的软件、重新登录的账号等，Agent 会另外列出。": "It includes the assistant, local files you choose and restoration instructions. The Agent separately lists software to reinstall and accounts to sign in to.",
  "我还有其他资料要一起带走": "I have other files to take too",
  "接入现有 AI Carry": "Use an existing AI Carry",
  "准备换电脑": "Prepare a computer move",
  "预览新 Agent 的接手请求": "Preview the new Agent handoff",
  "让 Agent 帮我准备迁移包": "Ask Agent to prepare a migration package",
  "把这段请求发给新 Agent，不用重新创建助手。": "Send this to the new Agent. You do not need another assistant.",
  "打包在本机完成，旧电脑内容不会被删除。": "Packaging happens locally. The old computer's files are not deleted.",
  "本地资料与备份": "Local files & backups",
  "哪些资料会被带走？": "Which files will be included?",
  "Agent 会列出已经知道的资料，也会问你是否有遗漏。哪些带走、哪些留在原处，会在打包前说清楚。": "The Agent lists known files and asks about anything missing. It explains what is included and what stays before packaging.",
  "准备导出": "prepare an export",
  "引导恢复": "guide restoration",
  "核对备份范围": "review backup contents",
  "让 Agent 说明新版改了什么，再决定是否升级。": "Ask the Agent what changed, then decide whether to upgrade.",
  "检查 AI Carry 新版": "Check for an AI Carry update",
  "让 Agent 检查新版": "Ask Agent to check for updates",
  "我的东西会被覆盖吗？": "Will my files be overwritten?",
  "你的记忆、SOP、Skill 和私人资料会保留。若某个组件需要适配，Agent 会单独说明和处理，不用因此停下其他工作。": "Memories, SOPs, Skills and private files are preserved. Components needing adaptation are handled separately without stopping unrelated work.",
  "哪里用着不对？": "Something not working?",
  "不用自己找日志。Agent 会问清经过，帮你分析并整理报告。": "No need to find logs yourself. The Agent asks what happened, investigates and prepares a report.",
  "Agent 会先去除报告中的私人信息，由你决定是否发送。": "The Agent removes private information from the report. You decide whether to send it.",
  "开始整理问题报告": "Prepare a problem report",
  "整理 Skill": "Create a Skill",
  "准备好的请求": "Prepared request",
  "你想用的 Agent": "Your chosen Agent",
  "粘贴请求": "Paste request",
  "发送": "Send",
  "Agent 的回复": "Agent reply",
  "文件与结果": "Files & results",
  "客户端使用说明": "How to use AI Carry",
  "在这里选，": "Choose it here.",
  "交给 Agent 做。": "Let your Agent do it.",
  "不用连接 Agent。复制请求，发到你想用的对话里。": "No Agent connection needed. Copy a request and send it in the conversation you choose.",
  "选一件事": "Choose a task",
  "怎么选择要做的事？": "How do I choose a task?",
  "点击客户端中的功能按钮，例如创建助手或整理 Skill，就会打开请求预览。你可以先看内容，也可以补充自己的要求。": "Click a feature such as assistant setup or Skill creation to preview its request. Review it and add details if needed.",
  "点击功能按钮，预览准备好的请求。": "Click a feature to preview its request.",
  "复制，发给 Agent": "Copy and send to your Agent",
  "复制后发到哪里？": "Where do I send the request?",
  "点击“复制请求”，切换到你想用的 Agent，把请求粘贴到对话框里，再点击发送。客户端不会替你发送；独立的任务也可以另开对话处理。": "Click “Copy request”, switch to your chosen Agent, paste into its conversation and send. AI Carry does not send it for you. Independent work can use a new conversation.",
  "复制请求，在 Agent 对话里粘贴并发送。": "Copy, paste into an Agent conversation, and send.",
  "在 Agent 看结果": "See results in your Agent",
  "在哪里看回复和文件？": "Where are replies and files?",
  "在你发送请求的 Agent 对话里查看回复和文件位置，也可以继续提问或修改。客户端不会接收这段对话；如果助手资料有更新，再回客户端重新读取。": "See replies and file locations in the Agent conversation where you sent the request. Continue discussing there. AI Carry does not receive the conversation; reload its files when the assistant's saved content changes.",
  "在同一段对话里查看回复、文件和下一步。": "Find replies, files and the next step in that conversation.",
  "助手资料更新后，回客户端重新读取。": "After assistant files change, return here and reload.",
  "怎样更新客户端显示的资料？": "How do I refresh the displayed content?",
  "回到“我的积累”等资料页面，点击“重新读取”。这里会展示 Agent 已经保存到助手文件夹的内容；重新读取不会替你执行任务。": "Open a data page such as My collection and click “Reload files”. It shows content your Agent saved in the assistant folder. Reloading does not execute a task.",
  "去选一件事": "Choose a task",
  "ZIP 压缩包": "ZIP archive",
  "方便发给别人": "Easy to send",
  "独立文件夹": "Folder",
  "方便查看和修改": "Easy to inspect and edit",
  "分享链接": "Share link",
  "生成前确认发布位置": "Choose a destination first",
  "先留在本机": "Keep locally",
  "暂时不分享": "Do not share yet",
  "固定流程 · SOP": "Workflow · SOP",
  "待完成": "In progress",
  "内容已检查": "Content checked",
  "内容已通过检查。可以请 Agent 确认文件位置，再准备压缩包、文件夹或分享链接。": "The content has been checked. Ask the Agent to confirm the files, then prepare a ZIP, folder or share link.",
  "这份 Skill 还有需要确认的地方。请 Agent 说明问题，再继续完善。": "This Skill still needs review. Ask the Agent to explain what is missing and continue.",
  "内容还没整理完。可以请 Agent 接着做，不用重新生成。": "The content is unfinished. Ask the Agent to continue rather than recreate it.",
  "请 Agent 准备分享": "Ask Agent to prepare sharing",
  "请 Agent 检查问题": "Ask Agent to inspect the issue",
  "请 Agent 继续整理": "Ask Agent to continue",
  "分享文件已准备": "Share files ready",
  "可以使用": "Available",
  "暂时不可用": "Temporarily unavailable",
  "已接入这份助手。把要做的任务告诉 Agent，它会判断这份 Skill 是否适用。": "Installed in this assistant. Tell the Agent your task and it will assess whether this Skill fits.",
  "请 Agent 查清这份 Skill 为什么暂时不能用，再帮你处理。其他 Skill 可以继续使用。": "Ask the Agent why this Skill is unavailable and how to recover it. Other Skills remain usable.",
  "让 Agent 使用这份 Skill": "Ask Agent to use this Skill",
  "让 Agent 检查并处理": "Ask Agent to inspect and resolve",
  "请粘贴 Skill 的网页链接。": "Paste the Skill's web link.",
  "Skill 文件夹": "Skill folder",
  "检查这份 Skill": "Check this Skill",
  "把常用方法做成 Skill，也能导入别人分享的 Skill。": "Turn methods into Skills or bring in Skills shared by others.",
  "Skill 是什么？": "What is a Skill?",
  "Skill 是一份给 Agent 使用的方法包，里面说明适合做什么、具体怎么做。你可以分享自己的，也可以安装别人分享的。": "A Skill is a method package for an Agent. It explains when and how to use it. Share your own or install one from someone else.",
  "Skill 工坊分区": "Skill workshop sections",
  "整理并分享": "Create & share",
  "接入别人的 Skill": "Import a Skill",
  "还没有可以整理的方法。保存为 SOP 或能力后，就能在这里选择并做成 Skill。": "No methods to turn into Skills yet. Once a method is saved as an SOP or capability, you can select it here.",
  "先在上方选择助手文件夹，查看可以整理的方法。": "Choose an assistant folder above to see methods you can turn into Skills.",
  "为什么推荐这些？": "Why these suggestions?",
  "这里列出已保存的方法供你选择。Agent 会读取正文，判断哪些步骤适合整理给别人用；不做成 Skill，也不影响原来的方法。": "Choose from your saved methods. The Agent reads the source to assess what can help others. The original method works whether or not you turn it into a Skill.",
  "先选一个你想分享的方法。": "Choose a method you want to share.",
  "原方法会保留，私人信息由 Agent 在副本中处理。": "Your original stays intact. The Agent removes private information in a copy.",
  "把这个方法整理为 Skill": "Turn this method into a Skill",
  "当前建议的依据": "Why this is suggested",
  "看看会整理哪些内容": "See what will be included",
  "。Agent 会读取原方法，保留有用的步骤，再整理成适合分享的版本。": ". The Agent reads the original method and keeps useful steps in a shareable version.",
  "你想怎样分享？": "How would you like to share?",
  "选链接会直接发布吗？": "Does choosing a link publish immediately?",
  "不会。Agent 会先问你想发布到哪里、哪些内容可以公开，再准备 Skill；发布前还会与你确认。也可以先留在本机。": "No. The Agent asks where to publish and what may be public, prepares the Skill, then checks with you before publishing. You can also keep it locally.",
  "分享方式": "Delivery format",
  "Agent 会先复制原方法，自动去除私人信息，再整理并检查 Skill。": "The Agent copies the original, removes private information, then prepares and checks the Skill.",
  "原方法保留，不会自动上传或发送。": "The original stays intact. Nothing is automatically uploaded or sent.",
  "整理为可分享的 Skill": "Create a shareable Skill",
  "让 Agent 整理为 Skill": "Ask Agent to create a Skill",
  "把别人的 Skill，": "Someone else's Skill,",
  "用到你的助手里。": "ready for your assistant.",
  "选一个文件夹、压缩包，或粘贴链接。": "Choose a folder or ZIP, or paste a link.",
  "Agent 会先检查，再引导你安装。": "The Agent checks it first, then guides installation.",
  "已经有旧版怎么办？": "What if I have an older version?",
  "Agent 会先判断是不是同一个 Skill 的新版，说明变化并保留你的设置和资料。来源不清楚时会先问你，不会直接覆盖旧版。": "The Agent checks whether this is an update to the same Skill, explains the changes and preserves your settings and files. Unclear origins are discussed before replacing anything.",
  "Skill 放在哪里？": "Where is the Skill?",
  "Skill 来源类型": "Skill source type",
  "文件夹": "Folder",
  "网页链接": "Web link",
  "Skill 的网页链接": "Skill URL",
  "ZIP 文件位置": "ZIP file location",
  "Skill 文件夹位置": "Skill folder location",
  "例如：Skill 所在的 GitHub 页面": "For example, the Skill's GitHub page",
  "点击右侧图标选择，或粘贴路径": "Choose with the folder icon, or paste a path",
  "粘贴完整路径，或点下方“帮我找到 Skill”": "Paste the full path, or choose “Help me find the Skill”",
  "正在选择…": "Choosing…",
  "选择 ZIP 文件": "Choose ZIP file",
  "选择文件夹": "Choose folder",
  "选好后复制请求，发给 Agent 检查。不会自动上传或安装。": "Copy the request and send it to your Agent for inspection. Nothing is uploaded or installed automatically.",
  "让 Agent 检查这份 Skill": "Ask Agent to check this Skill",
  "先找到 Skill 的位置": "Find the Skill first",
  "帮我找到 Skill": "Help me find the Skill",
  "Agent 会检查用途、脚本和所需权限。": "The Agent checks the purpose, scripts and required permissions.",
  "发现问题只处理这份 Skill，其他能力照常使用。": "Issues affect this Skill only. Other capabilities stay available.",
  "我的 Skill 类型": "My Skill categories",
  "我整理的": "Created by me",
  "已接入的": "Installed",
  "点开查看用途、状态和可做的操作。": "Open a Skill to see its purpose, status and available actions.",
  "先选择助手文件夹，查看已有的 Skill。": "Choose an assistant folder to see its Skills.",
  "还没有整理过 Skill。可以在“整理并分享”中选择一个方法。": "No created Skills yet. Choose a method under Create & share.",
  "还没有接入 Skill。可以从“接入别人的 Skill”开始。": "No installed Skills yet. Start with Import a Skill.",
  "示例：": "Example: ",
  "复制请求，再发给你想用的 Agent。": "Copy the request, then send it to the Agent you want.",
  "没有读到看板资料。仍可复制请求，让 Agent 从助手目录重新生成看板。": "Dashboard data could not be read. You can still copy a request asking your Agent to rebuild it from the assistant folder.",
  "本次没有读到新资料，原有内容仍可查看。可以重试，或请 Agent 重新生成看板。": "No new data was read. Existing content remains visible. Retry or ask your Agent to rebuild the dashboard.",
  "本次重新读取失败。原有内容仍可查看；请确认本地 snapshot.js 仍在。": "Reload failed. Existing content remains visible; check that the local snapshot.js is still present.",
  "这项操作没有完成，其他页面仍可用。": "This action did not finish. Other pages are still available.",
  "这条记录不在当前快照中。可以重新读取，或让 Agent 按条目找到原资料。": "This record is not in the current snapshot. Reload or ask your Agent to locate its source.",
  "网页保存的是摘要。让 Agent 读取这条记录，可查看完整正文。": "The web view keeps a summary. Ask your Agent to read the record for its full content.",
  "浏览器不允许自动复制，请选中全文后手动复制。": "This browser does not allow automatic copying. Select all and copy manually.",
  "浏览器不能取得完整本机路径。请粘贴路径，或用桌面客户端旁边的文件夹按钮选择。": "Browsers cannot retrieve a full local path. Paste it or use the desktop app's folder button.",
  "网页版使用当前目录的资料。要查看另一份助手，请打开那份助手的网页入口。": "This web view uses its own folder. Open the other assistant's web shortcut to view it."
};
